#!/usr/bin/env sh

cd ${0%/*} || exit 1    # run from this directory

#cp -rf ../examples/cavity .
cd cavity
#mv system/controlDict system/controlDictOld
#sed -e 's!endTime         900;!endTime         100;!g' system/controlDictOld > system/controlDict;
#rm system/controlDictOld
#./Allrun
cmp -s ../cavityResult.txt postProcessing/surfaces/100/gamma_L_interface.raw
cd ..