#!/bin/bash

cd ${0%/*} || exit 1 # run from this directory

./ConvergenceTestClean

for numCells in 320 640 1280
do
    printf "%s\n" "Simulation using ${numCells} cells:"
    cp -r stefanProblem stefanProblem_$numCells
    sed -i 's/ hex (0 1 2 3 4 5 6 7) (100 1 1) simpleGrading (1 1 1)/ hex (0 1 2 3 4 5 6 7) ('$numCells' 1 1) simpleGrading (1 1 1)/g' stefanProblem_$numCells/system/blockMeshDict
    cd stefanProblem_$numCells
    ./Allrun
    cd ..
done
