#!/bin/bash

cd ${0%/*} || exit 1 # run from this directory

./Allclean

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh

[ ! -d 0 ] && cp -r 0.orig 0

runApplication decomposePar

runParallel $(getApplication) &

runApplication reconstructPar

runParallel postProcess -func surfaces